import fs from "node:fs";
import path from "node:path";

/**
 * Asset manager — a small Vite plugin.
 *
 * Scans the `public/` directory and generates `src/assetsMap.ts`, a typed map
 * from each file's exact name to its served path (e.g. "loginImageBg.png" ->
 * "/images/loginImageBg.png"). Runs automatically on `npm run dev` (and build),
 * and regenerates when files are added/removed from `public/` during dev.
 *
 * Why a plugin instead of a standalone script: it hooks straight into Vite's
 * lifecycle, so there is nothing extra to remember to run and no new runtime
 * dependency to install.
 */

const PUBLIC_DIR = "public";
const OUTPUT_FILE = path.join("src", "assetsMap.ts");

/** Recursively collect every file under `dir`, relative to `baseDir`. */
function collectFiles(dir, baseDir, files = []) {
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			collectFiles(fullPath, baseDir, files);
		} else if (entry.isFile()) {
			// Served path relative to the public root, POSIX-style, leading slash.
			const relative = path.relative(baseDir, fullPath).split(path.sep).join("/");
			files.push({ name: entry.name, servedPath: `/${relative}` });
		}
	}
	return files;
}

/** Scan `public/` and (re)write `src/assetsMap.ts` if its contents changed. */
function generateAssetsMap(root) {
	const publicDir = path.resolve(root, PUBLIC_DIR);
	if (!fs.existsSync(publicDir)) {
		console.warn(`[assetsManager] "${PUBLIC_DIR}" directory not found — skipped.`);
		return;
	}

	const files = collectFiles(publicDir, publicDir);

	const map = {};
	for (const file of files) {
		if (map[file.name] && map[file.name] !== file.servedPath) {
			console.warn(
				`[assetsManager] Duplicate asset name "${file.name}": ` +
					`"${map[file.name]}" replaced by "${file.servedPath}".`,
			);
		}
		map[file.name] = file.servedPath;
	}

	const names = Object.keys(map).sort();
	const entries = names
		.map((name) => `\t${JSON.stringify(name)}: ${JSON.stringify(map[name])},`)
		.join("\n");

	const content = `// AUTO-GENERATED by assetsManager.js — do not edit manually.
// Maps every file in /public by its exact file name to its served path.

export const assetsMap = {
${entries}
} as const;

export type AssetName = keyof typeof assetsMap;
`;

	const outputPath = path.resolve(root, OUTPUT_FILE);
	const previous = fs.existsSync(outputPath)
		? fs.readFileSync(outputPath, "utf8")
		: "";

	if (previous !== content) {
		fs.writeFileSync(outputPath, content, "utf8");
		console.log(`[assetsManager] Wrote ${OUTPUT_FILE} (${names.length} assets).`);
	}
}

/** Vite plugin entry point. */
export function assetsManager() {
	let root = process.cwd();

	return {
		name: "assets-manager",
		configResolved(config) {
			root = config.root ?? root;
		},
		// Runs for both `vite dev` and `vite build`.
		buildStart() {
			generateAssetsMap(root);
		},
		// Keep the map in sync while the dev server is running.
		configureServer(server) {
			const publicDir = path.resolve(root, PUBLIC_DIR);
			server.watcher.add(publicDir);

			const onAssetChange = (file) => {
				if (file.startsWith(publicDir)) {
					generateAssetsMap(root);
				}
			};

			server.watcher.on("add", onAssetChange);
			server.watcher.on("unlink", onAssetChange);
		},
	};
}

export default assetsManager;
