export const homePageMetersMock = [
	{
		id: "COD",
		current: 5,
		goodThreshold: "10%",
		badThreshold: 80,
		name: "COD",
		unit: "kW/h",
	},
	{
		id: "BOD5",
		current: 54,
		goodThreshold: "10%",
		badThreshold: 80,
		name: "BOD5",
		unit: "mg/l",
	},
	{
		id: "Dầu mỡ",
		current: 66,
		goodThreshold: "10%",
		badThreshold: 60,
		name: "Dầu mỡ",
		unit: "kW/h",
	},
	{
		id: "PO4",
		current: 5,
		goodThreshold: "10%",
		badThreshold: 80,
		name: "PO4",
		unit: "kW/h",
	},
	{
		id: "FLOW",
		current: 13.5,
		goodThreshold: "10%",
		badThreshold: "80%",
		name: "FLOW",
		unit: "m3/day",
	},
	{
		id: "COD",
		current: undefined,
		goodThreshold: "10%",
		badThreshold: 80,
		name: "COD",
		unit: "kW/h",
	},
	{
		id: "COD",
		current: 100,
		goodThreshold: "10%",
		badThreshold: 80,
		name: "COD",
		unit: "kW/h",
	},
	{
		id: "BOD5",
		current: 54,
		goodThreshold: "10%",
		badThreshold: 80,
		name: "BOD5",
		unit: "mg/l",
	},
	{
		id: "Dầu nhờn ",
		current: undefined,
		goodThreshold: "10%",
		badThreshold: 60,
		name: "Dầu mỡ",
		unit: "kW/h",
	},
	{
		id: "PO4",
		current: 15,
		goodThreshold: "10%",
		badThreshold: 80,
		name: "PO4",
		unit: "kW/h",
	},
	{
		id: "FLOW",
		current: 13.5,
		goodThreshold: "10%",
		badThreshold: "80%",
		name: "FLOW",
		unit: "m3/day",
	},
	{
		id: "COD",
		current: 5,
		goodThreshold: "10%",
		badThreshold: 80,
		name: "COD",
		unit: "kW/h",
	},
];
