// AUTO-GENERATED by assetsManager.js — do not edit manually.
// Maps every file in /public by its exact file name to its served path.

export const assetsMap = {
	"favicon.ico": "/favicon.ico",
	"loginImageBg.png": "/images/loginImageBg.png",
	"logo192.png": "/logo192.png",
	"logo512.png": "/logo512.png",
	"manifest.json": "/manifest.json",
	"robots.txt": "/robots.txt",
	"stscLogo.png": "/images/stscLogo.png",
} as const;

export type AssetName = keyof typeof assetsMap;
